image:
  file: .gitpod.dockerfile

# Do we need to do it in a virtualenv ?
tasks:
  - init: virtualenv -p python3 env &&
          source env/bin/activate &&
          pip3 install -r requirements.txt
