service: tfrecord-builder
runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START gae_flex_pubsub_env]
env_variables:
    PUBSUB_TOPIC: topic_tfrecord
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: ok123456
    BUCKET_NAME: bucket03y
# [END gae_flex_pubsub_env]
